<a href="https://colab.research.google.com/github/Lbrb2/Aulas-Visualiza-o-e-an-lise-de-dados/blob/main/AulaNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
minhaLista = [0,1,2,3,4,5,6,7,8]

minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array3 = np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [ ]:
array3 = np.arange(0,10,0.5,dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
array4 = np.arange(12)

In [ ]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
type(array4)
array4.dtype

dtype('float64')

In [ ]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)
print(vetor1[3])
vetor1[0:2]

[0 1 2 3 4]
3


array([0, 1])

In [ ]:
s = np.array(['Python','Profissional','Java','Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [ ]:
s = np.array(['Python',146321315,'Profissional','Java','Água'])
s

array(['Python', '146321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [ ]:
vetor1[2] = 10
vetor1
vetor1[0] = 'Novo elemento'
vetor1
vetor1[0] = 45.6
vetor1

ValueError: invalid literal for int() with base 10: 'Novo elemento'

In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)
arr3 = np.arange(10,20,2)
arr4 = np.arange(10,20,1.4)

In [ ]:
arr5 = np.linspace(10,20,11)
arr6 = np.linspace(10,20,101)
arr7 = np.linspace(0,np.pi,100)

In [ ]:
minhaMatriz = np.array([[1,2,3],[4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
minhaLista = [[13,81,22],[0,34,59],[21,48,94]]
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [44]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [45]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
x = np.ones((4,4))
x

In [49]:
x = 8*np.ones((4,4))
x

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [50]:
z = np.diag(np.array([1,2,3,4,5,6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [52]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.shape(minhaMatriz)

(3, 3)

In [54]:
type(minhaMatriz)
minhaMatriz.dtype

dtype('int64')

In [55]:
minhaMatriz[2,1]
minhaMatriz[2,1]=100
minhaMatriz

matrix([[ 13,  81,  22],
        [  0,  34,  59],
        [ 21, 100,  94]])

In [57]:
np.sum(vetor1)

np.int64(18)

In [60]:
np.prod(vetor1)

np.int64(0)

In [61]:
np.cumsum(vetor1)

array([ 0,  1, 11, 14, 18])

In [70]:
vetor1.min()

np.int64(0)

In [71]:
vetor1.max()

np.int64(10)

In [72]:
np.mean(minhaMatriz)

np.float64(47.111111111111114)

In [73]:
np.median(minhaMatriz)

matrix([[  0.,  13.,  21.,  22.,  34.,  59.,  81.,  94., 100.]])

In [74]:
np.var(minhaMatriz)

np.float64(1239.2098765432102)

In [75]:
np.std(minhaMatriz)

np.float64(35.20241293637711)

In [81]:
meuarray10 = np.linspace(1,21,20)
meuarray10

array([ 1.        ,  2.05263158,  3.10526316,  4.15789474,  5.21052632,
        6.26315789,  7.31578947,  8.36842105,  9.42105263, 10.47368421,
       11.52631579, 12.57894737, 13.63157895, 14.68421053, 15.73684211,
       16.78947368, 17.84210526, 18.89473684, 19.94736842, 21.        ])

In [83]:
np.mean(meuarray10)

np.float64(11.0)

In [84]:
meuarray10.min()

np.float64(1.0)

In [85]:
meuarray10.max()

np.float64(21.0)

In [86]:
np.std(meuarray10)

np.float64(6.06976978666884)

In [87]:
np.var(meuarray10)

np.float64(36.8421052631579)